### ISSUE TITLE
Javascript updater script throws an error on page load.

### ISSUE THREAD

**Issue by mitchellblaser** [mitchellblaser/LunarPrintfarm#1]
Introduced in commit `8891b0afe874561dddbf2b9085a8f37a0b303300`.
This is because the script `update-index.js` does an asynchronous HTTP GET Request, and it doesn't wait for that to finish before it tries to access the variable and parse it to fill out the fields on the HTML Page.
There are a couple of ways to fix this but the easiest is probably to just pre-initialise that variable so it fills with empty info before the GET request completes.

**Comment by R-Tomas-Gonzalez** [comment]
Hi @mitchellblaser,

Can I try this out?

**Comment by mitchellblaser** [comment]
@R-Tomas-Gonzalez Go for it! I'm pretty tied up with backend stuff right now so an extra hand would be great.

**Comment by R-Tomas-Gonzalez** [comment]
Hey @mitchellblaser,

I added the var for info. Will you let me know if that works for you?

Thanks,

- Tomas

**Comment by mitchellblaser** [comment]
Looks good, thanks! I'll merge that in the morning when I'm a bit more awake. Looks like I need to update the .gitignore a bit more too.

**Comment by mitchellblaser** [comment]
Actually, that introduced another issue - you were initialising the variable every time rather than just once on page load.
Fixed that now in commit `133aac132cba5edb56ebec20dc4df7589bdc4ea2`.

**Comment by R-Tomas-Gonzalez** [comment]
Great. Sorry about that. Hope it helps! Cheers
