### ISSUE TITLE
(CSS) Hover Button Alignment on Queue Page isn't correct

### ISSUE THREAD

**Issue by mitchellblaser** [mitchellblaser/LunarPrintfarm#3]
Introduced in commit `1d839eb8d467097c99244cdfcdb8533c5bb8c006 `.
Every day I am reminded how bad I am at HTML/CSS. The buttons which appear on each list item on hover are not properly aligned to the far right of the list. Someone smarter than me can come and fix this but it's not something that actually is causing issues other than making it look slightly worse.

**Comment by whyprax** [comment]
Hello @mitchellblaser, I would like to work on this issue. Could you guide me on how I can start?
